TRAIN_DATASET = 'data/train.jsonl'
DEV_DATASET = 'data/dev.jsonl'
TEST_DATASET = 'data/test_unlabeled.jsonl'

GZIP_EXTENSION = '.gz'

TRAIN_DATASET_COMPRESSED = TRAIN_DATASET + GZIP_EXTENSION
DEV_DATASET_COMPRESSED = DEV_DATASET + GZIP_EXTENSION
TEST_DATASET_COMPRESSED = TEST_DATASET + GZIP_EXTENSION
